### ISSUE TITLE
Can't save certificates through frontend

### ISSUE THREAD

**Issue by troffasky** [ITSec-Chile/Waf2Py#1]
Deployed on Debian 10.5 from source. Debian VM was built specifically for this, so I know that /opt/waf did not exist before installing.
The permissions on /opt/waf/nginx/etc/ssl don't allow the frontend to save the submitted certificates. You just get an error telling you to reload the page.
Nothing is logged anywhere to indicate this might be the problem, I had to dig through the code to find this.

**Comment by ch-rigu** [comment]
which version are you using ? compiled version or are you compiling it ?
be sure that the permissions are ok.
# adjust permissions
chown www-data /opt/waf/nginx/var/log/
chown www-data /opt/waf/nginx/etc/{sites-available,sites-enabled,modsecurity_conf,modsec_rules,backend,listen,ssl}
chown www-data -R /opt/waf/nginx/etc/{rewrite,crs}

**Comment by troffasky** [comment]
I built from source following instructions here: https://github.com/ITSec-Chile/Waf2Py#installation-steps yesterday.
I am not sure how to determine what the version is.
/home/www-data/waf2py_community/VERSION says Version 2.20.4-stable+timestamp.2020.05.03.05.18.50
Web interface says 1.0

**Comment by ch-rigu** [comment]
> I built from source

Ok, something may happened when this command got executed `chown www-data /opt/waf/nginx/etc/{sites-available,sites-enabled,modsecurity_conf,modsec_rules,backend,listen,ssl}` this command adjust the permissions in the ssl  folders.
Is working now ?
