### ISSUE TITLE
Need Support

### ISSUE THREAD

**Issue by arun81** [ITSec-Chile/Waf2Py#1]
Dear Team 

Good Day !!!!! Thanks for this Project .

Still I understand this Project is in Beta Phase right away 
 
Below still I have followed the below process for creating certain web-app

1 - Create a virtual IP
      --> Interfaces menu

2 - Create a new app
      --> Click "check" button
      --> Click "Deploy" button

3 - Configure the new app
      --> Websites running menu
      --> Click over the application
      --> Configure the backend
      --> Configure ports
      --> Configure certificates if 443 port is enabled
      --> Choose a virtual ip (previusly created on Interfaces menu)
      --> Press the "play" button to enable the new app
      --> Done.

But once my application is get added it is not reflecting in Website Running menu .

I have also attached screenshot for your understanding . 

What I am doing wrong . Please let me understand .

Thanks
![added_application](https://user-images.githubusercontent.com/13440263/43603968-27f6662a-96b2-11e8-90ee-5628da098f74.png)
![nothing_coming_website_running_tab](https://user-images.githubusercontent.com/13440263/43603969-28685456-96b2-11e8-8134-4b2faf4023b2.png)

**Comment by ch-rigu** [comment]
Hi @arun81 , after you create the app, you have to click on "Check (1)" button and then in status will change to "Ready to deploy", then just click on "Deploy (2)" button and it will be moved to the websites view.
In your first screenshot you have to press the "Deploy (2)" button.

Cheers.
Chris.

**Comment by arun81** [comment]
Hi Chris

Thanks for your Support and Revert 

After I Click on Deploy . I am getting following error .

Attached is the error 

![deploy](https://user-images.githubusercontent.com/13440263/43622013-c266f6c6-96f7-11e8-9552-e659af92580d.png)

**Comment by ch-rigu** [comment]
Hmm can you click on that ticket and showme the error please.

Thanks.

**Comment by ch-rigu** [comment]
@arun81 I think is a missing folder, the first commit was missing a necessary folder. 
I just created a new debian 9, then I've cloned this repo and everything is working properly :)

Please make a clone, try again and tell me if is ok.

Cheers.
Chris.

**Comment by arun81** [comment]
Hi 

Can you please close this issue for now as my debian version is unstable 

Can you please link me stable debian version and close this ticket 

Sorry  for the inconvenience 

Thanks

**Comment by ch-rigu** [comment]
Sure,
Debian 9
https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-9.5.0-amd64-netinst.iso

Cheers.
Chris.
