### ISSUE TITLE
Logs stop generating

### ISSUE THREAD

**Issue by deeztek** [ITSec-Chile/Waf2Py#10]
Hi, after about a month of uptime, it seems Waf2py stops ingesting attack logs. Clicking the Reload button does nothing.

**Comment by ch-rigu** [comment]
Hi, please provide more information about it. 
Are logs (/opt/waf/nginx/log/) files being created? 
There is visible error or something?

**Comment by deeztek** [comment]
no /opt/waf/nginx/log/ directory in my installation. I can see the attacks under the Error logs tab but they are not being displayed in the Attacks tab.

**Comment by ch-rigu** [comment]
The audit log is being populated?

**Comment by deeztek** [comment]
there seem to be audit logs in the /opt/waf/nginx/var/log/domain.tld directory but they don't have current timestamps (last one was from 4 days ago). They don't seem to be getting generated. I verified this by generating a sql injection attack on one of the websites and the attack log still doesn't have any entries but the Error log has the attack listed. The audit log is still 4 days old.

**Comment by ch-rigu** [comment]
Try reloading/restarting nginx from the left menu and check again if the
attack is being registered in the audit log.

I think this can be related to logrotation. For some reason, sometimes when
logrotation occurs and send the signal to nginx to recreate all the logs it
work with the access log and error log, but the audit log doesn't. I've
seen this behavior before and I don't know how to solve it. If this is the
case, a workaround would be restart nginx after logrotation occurs (but
this is not best way)... Or just remove logrotation from crontab. I'm no
aware if there is a special configuration to fix this.

Cheers.

**Comment by deeztek** [comment]
I already reloaded/restarted nginx and I even restarted the server. 

so, in the following script (logrotate), should I add a line to restart nginx?

```
test -x /usr/sbin/logrotate || exit 0
ls /home/www-data/waf2py_community/applications/Waf2Py/logrotation.d | while read i; do /usr/sbin/logrotate -v /home/www-data/waf2py_community/applications/Waf2Py/logrotation.d/$i;done
```

**Comment by ch-rigu** [comment]
With a simple restart of nginx is enough.
Yes, the line that restart nginx should be below the "ls /home/www-data/xxxxxxxxxx........" command.

**Comment by deeztek** [comment]
so, it should be something like this (not sure how to restart nginx) ?

```
test -x /usr/sbin/logrotate || exit 0
ls /home/www-data/waf2py_community/applications/Waf2Py/logrotation.d | while read i; do /usr/sbin/logrotate -v /home/www-data/waf2py_community/applications/Waf2Py/logrotation.d/$i;done
/opt/waf/nginx/sbin/nginx
```

**Comment by ch-rigu** [comment]
have a look to this: https://www.nginx.com/resources/wiki/start/topics/tutorials/commandline/ 

should be something like this:

```
test -x /usr/sbin/logrotate || exit 0
ls /home/www-data/waf2py_community/applications/Waf2Py/logrotation.d | while read i; do /usr/sbin/logrotate -v /home/www-data/waf2py_community/applications/Waf2Py/logrotation.d/$i;done
/opt/waf/nginx/sbin/nginx -s stop
/opt/waf/nginx/sbin/nginx -s start
```

nginx doesn't have a restart switch, so you need to stop it and then start it. 
Be in mind that this stop/reload process doesn't check if Syntax configuration is ok like the waf2py app does. So if you have edited/created a website with a syntax error it will fail to start.

**Comment by deeztek** [comment]
It actually seems to be as follows:

```
/opt/waf/nginx/sbin/nginx -s stop
/opt/waf/nginx/sbin/nginx
```

I'll try it and see what happens. I guess I can avoid the issue by ensuring that everytime I make a change or add a website to make sure I test nginx

**Comment by ch-rigu** [comment]
Hi @deeztek ,with the previous workaround the audit log is being written normally?

**Comment by deeztek** [comment]
The workaround doesn't seem to be working. I'm not sure if it's the workaround or the following error when I run the logrotate script:

> nginx: [emerg] "modsecurity_rules_file" directive Failed to allocate shared memory (1): Invalid argument in /opt/waf/nginx/etc/sites-enabled/domain.tld_nginx.conf:213

Looking at line 21 of the file I find the following entry:

> modsecurity_rules_file /opt/waf/nginx/etc/modsecurity_conf/domain.tld_modsec.conf; #Cambiar

I looked at other configuration files for other sites and they all look the same. Additionally, the *_modsec.conf files all seem to be empty.

So I removed the website and tried to run the logrotate script again. The above error was gone but then I got the following:

> nginx: [emerg] bind() to 192.168.xxx.xxx:80 failed (98: Address already in use)
> nginx: [emerg] bind() to 192.168.xxx.xxx:443 failed (98: Address already in use)
> nginx: [emerg] bind() to 192.168.xxx.xxx:80 failed (98: Address already in use)
> nginx: [emerg] bind() to 192.168.xxx.xxx:443 failed (98: Address already in use)
> nginx: [emerg] bind() to 192.168.xxx.xxx:80 failed (98: Address already in use)
> nginx: [emerg] bind() to 192.168.xxx.xxx:443 failed (98: Address already in use)
> nginx: [emerg] bind() to 192.168.xxx.xxx:80 failed (98: Address already in use)
> nginx: [emerg] bind() to 192.168.xxx.xxx:443 failed (98: Address already in use)
> nginx: [emerg] bind() to 192.168.xxx.xxx:80 failed (98: Address already in use)
> nginx: [emerg] bind() to 192.168.xxx.xxx:443 failed (98: Address already in use)
> nginx: [emerg] still could not bind()

nginx was not running at that point.  Obviously this is due to the fact that I added the following lines to the logrotate script:

> /opt/waf/nginx/sbin/nginx -s stop
> /opt/waf/nginx/sbin/nginx

I was able to go back to the web gui and restart nginx. 

there seems to be some type of disconnect between starting nginx from the command line and the web gui. Also, what's up with those errors?

I would appreciate some assistance on this.

Thanks

**Comment by deeztek** [comment]
A couple more issues:

1. If I have a website that does not require SSL, I leave the Ports HTTPS empty and I don't enter anything under the HTTPS section of the Real application IPs. However, when I save the website and deploy, the application insists on creating an SSL configuration so I have to manually go into the Expert Configuration section and comment out the following lines or nginx throws an error when trying to Reload or Start Stop the service:

> #ssl_certificate 
> #ssl_certificate_key 

2. When i create a website that does not have more than one server_name, for instance application.domain.tld, so I want nginx to only listen for application.domain.tld, the system forces me to fill out both the Application Name and the Application URL so I end up filling the same name in both fields and then the nginx config looks like this:

> server_name application.domain.tld application.domain.tld;

So, I have to manually go into Expert Configuration and remove the additional entry or nginx throws a bunch of errors.

**Comment by ch-rigu** [comment]
> A couple more issues:
> 
> If I have a website that does not require SSL, I leave the Ports HTTPS empty and I don't enter anything under the HTTPS section of the Real application IPs. However, when I save the website and deploy, the application insists on creating an SSL configuration so I have to manually go into the Expert Configuration section and comment out the following lines or nginx throws an error when trying to Reload or Start Stop the service:
> #ssl_certificate
> #ssl_certificate_key

> When i create a website that does not have more than one server_name, for instance application.domain.tld, so I want nginx to only listen for application.domain.tld, the system forces me to fill out both the Application Name and the Application URL so I end up filling the same name in both fields and then the nginx config looks like this:
> server_name application.domain.tld application.domain.tld;

this is Ok, the name of the app is just a name to save in db and to be showed and used internally.
the double "server_name application.domain.tld application.domain.tld;" is because when you create an app is intended to receive an app that start with "www", if that happens the "www" are striped ending like this "domain.tld application.domain.tld" 

> So, I have to manually go into Expert Configuration and remove the additional entry or nginx throws a bunch of errors.

Is not neccesary to remove the extra server name, nothing happens if you have the same name twice. Since I developed this app I never saw an error with this (and this haven't change since the begining). However, the server name line will be improved to work not only with the "www".

**Comment by deeztek** [comment]
> if you don't need SSL you just need to leave in blank the box where ssl ports should be.
> The app does not force you to use SSL if you leave in blank this field.

I do leave it blank but it still creates the SSL configuration in Nginx.

**Comment by ch-rigu** [comment]
Yes, tha app works like this, the lines are created and that is Ok.

Just leave in blank the ssl port field and and also "Real application
IPs HTTPS" field.

lines containing the ssl certificate are commented. So they doesn't
cause any problem.

Cheers.

**Comment by deeztek** [comment]
> lines containing the ssl certificate are commented. So they doesn't cause any problem. 

That's what I'm trying to tell you. The lines are NOT commented. I have to comment them out manually

**Comment by ch-rigu** [comment]
The workaround doesn't seem to be working. I'm not sure if it's the workaround or the following error when I run the logrotate script:

> nginx: [emerg] "modsecurity_rules_file" directive Failed to allocate shared memory (1): Invalid argument in /opt/waf/nginx/etc/sites-enabled/domain.tld_nginx.conf:213

> Looking at line 21 of the file I find the following entry:
> 
> > modsecurity_rules_file /opt/waf/nginx/etc/modsecurity_conf/domain.tld_modsec.conf; #Cambiar
> 
> I looked at other configuration files for other sites and they all look the same. Additionally, the *_modsec.conf files all seem to be empty.

This file should not be empty because is the whole configuration of modsec for the selected app. There is nothing in the app that delete those files, You only can rewrite this file throught the expert tab. if they are empty is because maybe you deleted them through the terminal or something

> So I removed the website and tried to run the logrotate script again. The above error was gone but then I got the following:
> 
> > nginx: [emerg] bind() to 192.168.xxx.xxx:80 failed (98: Address already in use)
> > nginx: [emerg] bind() to 192.168.xxx.xxx:443 failed (98: Address already in use)
> > nginx: [emerg] bind() to 192.168.xxx.xxx:80 failed (98: Address already in use)
> > nginx: [emerg] bind() to 192.168.xxx.xxx:443 failed (98: Address already in use)
> > nginx: [emerg] bind() to 192.168.xxx.xxx:80 failed (98: Address already in use)
> > nginx: [emerg] bind() to 192.168.xxx.xxx:443 failed (98: Address already in use)
> > nginx: [emerg] bind() to 192.168.xxx.xxx:80 failed (98: Address already in use)
> > nginx: [emerg] bind() to 192.168.xxx.xxx:443 failed (98: Address already in use)
> > nginx: [emerg] bind() to 192.168.xxx.xxx:80 failed (98: Address already in use)
> > nginx: [emerg] bind() to 192.168.xxx.xxx:443 failed (98: Address already in use)
> > nginx: [emerg] still could not bind()
> 
> nginx was not running at that point.  Obviously this is due to the fact that I added the following lines to the logrotate script:
> 
> > /opt/waf/nginx/sbin/nginx -s stop
> > /opt/waf/nginx/sbin/nginx
> 
> I was able to go back to the web gui and restart nginx. 
> 
> there seems to be some type of disconnect between starting nginx from the command line and the web gui. Also, what's up with those errors?
> 
> I would appreciate some assistance on this.
> 
> Thanks

I think the stop and start nginx is happen too fast, maybe a small delay between stop and start will fix this. Sometimes when you stop nginx it take some seconds until stops everything. That would explain "Addres already in use" message.
Try with a small delay between. 
I think this is something that need to be reported on modecurity github or nginx.

Cheers.

**Comment by deeztek** [comment]
> This file should not be empty because is the whole configuration of modsec for the selected app. There is nothing in the app that delete those files, You only can rewrite this file throught the expert tab. if they are empty is because maybe you deleted them through the terminal or something
> 

I can assure you, I did NOT remove the entries for one website, let alone ALL the websites. Nginx is still blocking, so how does that happen if the configuration file is empty?


> I think the stop and start nginx is happen too fast, maybe a small delay between stop and start will fix this. Sometimes when you stop nginx it take some seconds until stops everything. That would explain "Addres already in use" message.
> Try with a small delay between.
> I think this is something that need to be reported on modecurity github or nginx.
> 
> Cheers.

I can try with a delay and see what happens.

**Comment by ch-rigu** [comment]
> That's what I'm trying to tell you. The lines are NOT commented. I have to comment them out manually

Ok, I did some test and is working weird this part. This will be fixed.

**Comment by ch-rigu** [comment]
> I can assure you, I did NOT remove the entries for one website, let alone ALL the websites. Nginx is still blocking, so how does that happen if the configuration file is empty?

Is still working because there is no reload performed, waf2py doesn't reload the nginx if there is problem with the configuration.

**Comment by deeztek** [comment]
I don't think that's the case because I've reloaded/restarted nginx plenty of times since.

**Comment by deeztek** [comment]
What would the caveat be of completely disabling the logrotate script?

**Comment by deeztek** [comment]
I added sleep for 30 seconds and it seems to have ran successfully.
