### ISSUE TITLE
nginx: [emerg] unknown directive "set_real_ip_from"

### ISSUE THREAD

**Issue by deeztek** [ITSec-Chile/Waf2Py#12]
Apparently I'm not able to set the set_real_ip_from directive in the modsecurity config because the realip module is not installed. I'm trying to get waf2py to send the client IP instead of its own IP. How would I go about re-installing with the http_realip_module?

Thanks

**Comment by ch-rigu** [comment]
Maybe compiling again the openresty with the real_ip module without installing  it (just doing "make", not "make install") and the replacing the old nginx binary in /opt/waf/nginx/sbin/nginx (maybe the path is diferent, don't remember now) with the new one. Just do a backup of the whole waf folder (/opt/waf/), just in case...
in the "waf2py_installer.sh" are the esteps to compile openresty (nginx), just add the module that you need.
Cheers.
