### ISSUE TITLE
Dashboard Access - Internal Error

### ISSUE THREAD

**Issue by jrichard689** [ITSec-Chile/Waf2Py#2]
Hi,

Tahnk you for this new project, it sound great!

I have a problem, i can't acces the Dashboard:

![image](https://user-images.githubusercontent.com/31750975/43663694-3722581c-9706-11e8-9f03-d5bdb62ae4c4.png)
![image](https://user-images.githubusercontent.com/31750975/43663729-482ffb28-9706-11e8-9a8a-7224fa99527b.png)

Maybe i miss something?

Thank you

**Comment by ch-rigu** [comment]
Hi @jrichard689, Waf2Py is installed on a debian 9 or 8 machine ?
Can you make this command: /bin/df -h | /bin/grep sda1 | awk '{print $1,$2,$3,$4,$5}'  and show me the output ?
The dashboard shows info of sda1 disk, which is by default in a debian installation, if you have another disk, that might be the error

Cheers.

**Comment by jrichard689** [comment]
Thank you for your help.

I'm on a debian:
```
cat /etc/issue
Debian GNU/Linux 9 \n \l
```

in docker, maybe it's the problem.

When i run df in container, no sda1.

Regards.

**Comment by ch-rigu** [comment]
For this case you will have to edit de default.py on /home/www-data/waf2py_community/applications/Waf2Py/controllers/default.py on line 54 and change sda1 to your disk

Future release there will be a view to select the disk that you want to show in the dashboard.
Cheers.
Chris.

**Comment by jrichard689** [comment]
Thank you. Modify as you explain, now i see Dashboard.
