### ISSUE TITLE
Too many nginx_start_check.sh processes

### ISSUE THREAD

**Issue by troffasky** [ITSec-Chile/Waf2Py#2]
The nginx_start_check.sh script never seems to exit. I have 187 of these processes after 1h32m uptime.

**Comment by ch-rigu** [comment]
Hi, yes, is a bug, go to crontab as root and remove those lines with nginx_start_check" or just leave one. I Will fix it soon.

**Comment by ch-rigu** [comment]
fixed in commit: https://github.com/ITSec-Chile/Waf2Py/commit/25b6a0d1ff4f0f49734285529f4f29c87d21afeb
