### ISSUE TITLE
Permissions on /opt/waf/nginx/var/log/audit_logs/

### ISSUE THREAD

**Issue by troffasky** [ITSec-Chile/Waf2Py#3]
Permissions don't allow site's logs to be created which leads to mostly-empty stats for that site.

**Comment by ch-rigu** [comment]
Hi, logs should be "/opt/waf/nginx/var/log/Application_name" and inside should be the audit log.
how did you get this error ? (I haven't seen it)
/opt/waf/nginx/var/log/audit_logs folder is not used, maybe modec configuration is creating this folder this folder.

**Comment by troffasky** [comment]
I added the site following the instructions. 
You are right, there is nothing in /opt/waf/nginx/var/log/audit_logs/Application_name/.
I think I might have created audit_logs/Application_name because I have misinterpreted the code!
If audit_logs isn't the correct directory then I am not sure what it was that caused logs to start appearing. I am pretty sure it was >15 minutes after adding the site before logs appeared. All I can see in my bash_history is: chown -R www-data.www-data /opt/waf/nginx/var/log/audit_logs/
I will do another install at some point in the next few weeks.
I have also applied fixes from #1.

**Comment by troffasky** [comment]
It's not me misinterpreting the code, I found the path referenced in an error in /var/log/apache2/waf2py_error.log.

```
...
[Wed Aug 26 13:21:43.424633 2020] [ssl:warn] [pid 464:tid 140655334773888] AH01909: waf2py-demo.jtg.local:62443:0 server certificate does NOT include an ID which matches the server name
chown: cannot access '/opt/waf/nginx/var/log/audit_logs/Application_name': No such file or directory
[Wed Aug 26 13:40:56.031592 2020] [ssl:warn] [pid 457:tid 139963648775296] AH01906: waf2py-demo.jtg.local:62443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
...
```

**Comment by ch-rigu** [comment]
I will look that error today, anyway this should not be a problem.

**Comment by ch-rigu** [comment]
It was and old remains from waf2py beta, I removed the "audit_log" string. This does not interfere with functionality.
for an existing app: go to the "Expert configuration" tab and in the ModSecurity config and remove this lines:

`# Specify the path for concurrent audit logging.`
`#SecAuditLogType Concurrent`
`#SecAuditLogStorageDir /opt/waf/nginx/var/log/app_name/audit_logs`
`#SecAuditLog /opt/waf/nginx/var/log/app_name/audit_logs/id_app_name_audit.log`

You can make a git pull inside of /home/www-data/waf2py_community/applications/Waf2Py and all the new apps that you create will have the updated config.

First create a backup of `the/home/www-data/waf2py_community/applications/Waf2Py/databases` folder just in case, to avoid loose the apps created
