### ISSUE TITLE
Page 

### ISSUE THREAD

**Issue by arun81** [ITSec-Chile/Waf2Py#6]
Dear Team 

Thanks for your Support to provide the New Version of Waf2Py 

Installed Successfully in Debian 9 System but getting the Beta Error in Web Console ( attached <Beta-Error.png> )

Next When I am clicking System >> General Configuration .
 
Not able to Browse into SERVICES / MANAGE WAF / SYSTEM /LOGS ( attached <General-config.png> )

When I am Clicking Dashboard getting attached Dashboard-Error.png Error.

Please let me know what I am doing wrong .

Thanks
![beta-error](https://user-images.githubusercontent.com/13440263/52137197-0bf04880-2670-11e9-86b6-00a3965f6218.png)
![dashboard-error](https://user-images.githubusercontent.com/13440263/52137198-0c88df00-2670-11e9-88db-8260d005a6d6.png)
![general-config](https://user-images.githubusercontent.com/13440263/52137199-0c88df00-2670-11e9-9e69-e3d9086ef8ac.png)

**Comment by ch-rigu** [comment]
Hi arun81, did you copy the new (branch --branch waf2py_modsec3)?

Generalconfig  is  an old option that is not anymore, i forgot to remove
that.
there might be  links with wrong/old targets... I'm gonna clean that.
if you click on 'Dashboard' should be get you to /Dashboard (uppercase D)

Cheers.
Chris.

**Comment by ch-rigu** [comment]
Old entry from menu was removed!
You can make a pull and replace the Waf2Py folder in /home/www-data/waf2py_community/applications/ with the Waf2Py.zip for content, and the set proper user: chown www-data.www-data -R /home/www-data/waf2py_community/applications/Waf2Py

Cheers.
Chris.
