### ISSUE TITLE
Start Engine at bootup

### ISSUE THREAD

**Issue by deeztek** [ITSec-Chile/Waf2Py#7]
How would I go about setting WAF2Py engine to start automatically at bootup?

**Comment by ch-rigu** [comment]
For that exist an script in
/home/www-data/waf2py_community/applications/Waf2Py/scripts/check_services.py

That is executed at boot with a cron job.

I added this part just yesterday, if you cloned the repo before, you will
need to check make a pull and replace the Waf2Py folder in
/home/www-data/waf2py_community/applications/
with the Waf2Py.zip content.

Cheers
