### ISSUE TITLE
Virtual IP disappears on reboot

### ISSUE THREAD

**Issue by deeztek** [ITSec-Chile/Waf2Py#8]
After creating a virtual IP, if I reboot, the IP disappears from the machine configuration but Waf2Py still has the IP in its configuration. Then I can't create the virtual IP again because Waf2Py complains that the IP is already in use. If I try to delete the virtual IP, Waf2Py complains that it's in use by websites. 

The only way I could get it to work is by assigning an additional IP that matched the Waf2Py virtual IP in my network adapter.

**Comment by ch-rigu** [comment]
verify that you have the propers cron jobs for this, as root do crontab -l you should see this:

```
root@debian:/home/chris# crontab -l
@reboot  /usr/bin/python /home/www-data/waf2py_community/applications/Waf2Py/scripts/check_services.py
2 0 * * * /usr/bin/python /home/www-data/waf2py_community/applications/Waf2Py/scripts/index_logs_files.py
0 */2 * * * /bin/bash /home/www-data/waf2py_community/applications/Waf2Py/scripts/remove_tmp.sh
1 0 * * * /bin/bash /home/www-data/waf2py_community/applications/Waf2Py/scripts/logrotate
```
if you don't have this, add it (this was added in a previous commit [e0a4df7)](https://github.com/ITSec-Chile/Waf2Py/commit/e0a4df702796bb2a0d4a250e3e720135275b02de) .

The first line is in charge of bring up the virtual interfaces and start the nginx when a reboot happens
Cheers.
